name: high_q_paginated_drop_down
description: Package handles the pagination and search in DropDown .
version: 2.0.9
homepage: https://github.com/mazab99/high_q_paginated_drop_down

environment:
  sdk: '>=3.2.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  async: ^2.11.0

dev_dependencies:
  change_app_package_name: ^1.1.0
  recase: ^4.1.0
  flutter_test:
    sdk: flutter
  version: ^2.0.0
  flutter_lints: ^2.0.1
